### PR TITLE
add support for generic partitions

### PR DESCRIPTION
**Pull request by sashaostr**
using hive command "msck repair table", the util.py file can now support adding partitions with generic pattern

### CODE REVIEW

**Comment by ottomata** [comment]
Hi!

Thanks for the commit!  
1.  WMF is no longer using this repository, so it is unlikely that we will merge this.  However, this script is still useful.  Perhaps it should be in its own repository?
2.  Does MSCK REPAIR TABLE work for tables for which the HDFS hierarchy does not match the 'partition_key=partition_value' format?  The original purpose of this script was to support automatically partitioning data stored in HDFS like 'year/month/day/hour/'.

**Comment by ottomata** [comment]
Oo, new feature!  I am reading this now:
https://cwiki.apache.org/confluence/display/Hive/HCatalog+DynamicPartitions#HCatalogDynamicPartitions-ExternalTables

**Comment by ottomata** [comment]
Ah so, according to that link.  Hive 0.13's `MSCK REPAIR TABLE` can automatically add any newly created partition directories that don't have any partition meta data.  This means that even this patch won't really be necessary.  All one has to do is set `hcat.dynamic.partitioning.custom.pattern` appropriately and then run `MSCK REPAIR TABLE` and Hive will do the right thing.

**Comment by sashaostr** [comment]
Otto, thank you for comments. Looks like you found something that I missed. My purpose was to treat exactly the case when running MSCK command for external table didn't worked for me - it just printed out the  missed partitions path, so I parsed it and built the ALTER TABLE statement. Unfortunately I missed this particular link, that probably explains why that didn't worked for me.
Anyway I"ll test this property tomorrow on my installation and update.

**Pull request closed without merging**
