### PR TITLE
Email Oozie Failure

### PR DESCRIPTION
**Pull request by drdee**

### CODE REVIEW

**Comment by ottomata** [comment]
Oh hm.  I don' think we need xInclude for this, but it might be better?  I'm not sure.

Oozie can load sub workflows, which is how we are using coalesce in the first place.  We could just create a sub workflow that has this action for emailing.

Unless you think xInclude is better.  Other than that this sounds cool.  Did you test this with your own custom job somewhere?

**Comment by somechris** [comment]
Discussing this with ottomata, and dvanliere it turned out that xInclude might be better route for now, as (in case of failure), we are closer at the error-causing Job Id.

If we want to switch over to a sub-workflow mechanism later, we can wrap the xIncluded snippet in a workflow, and gradually switch over to using that sub-workflow.

**Comment by somechris** [comment]
The “kill” element does not accept nested actions or emails. It only takes “message” elements.

However, I tested adding an action that sends out an email about the
error and then forwards to the kill action. That works nicely.

Putting that in a separate file and including that file from workflow jobs 
should just do the trick.

Is there a way to add other patches to a pull request (as in gerrit),
or should I rather put that in a separate pull request?

**Comment by somechris** [comment]
> [...] and including that file [...]

It turns out that this really is the hard part :-( In contrast to what
this pull request's patch suggests, I could not find any xInclude
support in workflow job specifications with Oozie on CDH4.
Do we have xInclude support?

So I tried the ottomata's alternative suggestion of sub-workflows. It
turned out that the job-id problem isn't too much of a problem. We can
pass the name, ... of the failed action to the sub-workflow by adding
some properties.

And as Oozie spawn's a separate job for the sub-workflow, we get two
separate job-ids and two statuses. So we can distinguish between the
main workflow and the error handling. Especially, we can get the main
workflow to be marked as KILLED if some action failed. So we notice
failure by only looking at the main workflow.

The downside of this solution is that (due to having to set some
properties) the workflow job specifications grow by ~30 lines of the
same code in every file. However, we need not change this code even if
error handling changes. Such changes can now be incorporated into the
sub-workflow.

The following possibilities come to my mind:
- Use sub-workflows nonetheless
  Pros:
  *\* When changes in reporting become necessary, we need not touch the
  workflow specifications.
  Cons:
  *\* Needs ~30 lines of code in each wokflow job specification.
- Implement custom action that does all the reporting.
  Pro:
  *\* When changes in reporting become necessary, we need not touch the
  workflow specifications.
  *\* Only 4 lines of code in workflow specification.
  Cons:
  *\* Probably a Java solution.
- Add a xml preprocessing step to do the including of the common parts
  Pro:
  *\* When changes in reporting become necessary, we need not touch the
  workflow specifications.
  *\* Would allow to use the full power of XML in workflow job
  specifications
  Cons:
  *\* We cannot directly deploy a local file, but need to invoke the
  preprocessing (e.g.: run “make”)
- Add a watchdog to oozie.
  The watchdog would poll oozie job stats and send an email if it detecs
  failed jobs.
  Pro:
  *\* When changes in reporting become necessary, we need not touch the
  workflow specifications.
  *\* Works without touching oozie
  *\* No Java needed
  Cons:
  *\* We need to make sure the watchdog is running and working.
  *\* Per se not very flexible
  *\* Might produce false positives with sub-workflows that fail, but main
  workflow can make up for the failure
- Add the email action by hand in ever workflow job file
  Pro:
  *\* Works without touching oozie
  Cons:
  *\* Maintenance nightmare
- Totally awesome new approach
  Pro:
  *\* ...
  Cons:
  *\* ...

**Pull request merged**
